Input_1=float(input("Enter a number:"))
Input_2=float(input("Enter a number:"))
print("Sum of two numbers is:", Input_1+Input_2)
print("Subtraction of two numbers is:", Input_1-Input_2)
print("Multiplication of two numbers is:", Input_1*Input_2)
print("Division of two numbers is:", Input_1/Input_2)
